### PR TITLE
Patch for FOP-3077 Wrong rendering of LATIN SMALL LETTER J WITH COMBINING ACUTE ACCENT

### PR DESCRIPTION
**Pull request by vk-github18**
Update GlyphSubstitutionTable.java
Process all rulesets

### CODE REVIEW

**Comment by infosuitemka** [comment]
I am out of the office until 08-08-2022.

Please contact InfoSuite support at ***@***.*** for assistance.


Note: This is an automated response to your message  "[apache/xmlgraphics-fop] Patch for FOP-3077 Wrong rendering of LATIN SMALL LETTER J WITH COMBINING ACUTE ACCENT (PR #70)"( sent on 05-08-2022 00:08:39) . 

This is the only notification you will receive while this person is away.

**Comment by vk-github18** [comment]
Patch has been applied in SVN

**Comment by infosuitemka** [comment]
I am out of the office until 08-08-2022.

Please contact InfoSuite support at ***@***.*** for assistance.


Note: This is an automated response to your message  "Re: [apache/xmlgraphics-fop] Patch for FOP-3077 Wrong rendering of LATIN SMALL LETTER J WITH COMBINING ACUTE ACCENT (PR #70)"( sent on 05-08-2022 15:32:43) . 

This is the only notification you will receive while this person is away.

**Comment by infosuitemka** [comment]
I am out of the office until 08-08-2022.

Please contact InfoSuite support at ***@***.*** for assistance.


Note: This is an automated response to your message  "Re: [apache/xmlgraphics-fop] Patch for FOP-3077 Wrong rendering of LATIN SMALL LETTER J WITH COMBINING ACUTE ACCENT (PR #70)"( sent on 05-08-2022 15:31:55) . 

This is the only notification you will receive while this person is away.

**Pull request closed without merging**
